### ISSUE TITLE
Add more documentation on usage

### ISSUE THREAD

**Issue by dparv** [canonical/iam-bundle#218]
### Enhancement Proposal

I just deployed it and accessed both IPs from traefik (public and admin) and I get 404 page not found - what are the use cases? How can I integrate with other charms? Please document some usage scenarios.

**Comment by nsklikas** [comment]
Which pages did you try to access? One hydra endpoint you should try is `.well-known/openid-configuration`.

The use case for this version is OIDC/OAuth2 brokering. You can have a look at https://charmhub.io/topics/canonical-identity-platform for more info. 

Please try to provide more info if you are still facing issues.

**Comment by dparv** [comment]
@nsklikas how can I for example use the identity provider to manage users and use as OIDC for an application? E.g. I don't want an external OIDC, but to rely on the Canonical IAM for user management, is that possible?

**Comment by natalian98** [comment]
The documentation has been updated and published: https://charmhub.io/topics/canonical-identity-platform/tutorials/e2e-tutorial
https://charmhub.io/topics/canonical-identity-platform/how-to

We added info on the local identity provider.
I will close this ticket, but please feel free to reopen in case you are still facing issues.
