### ISSUE TITLE
Investigate failed tests workflow in main branch

### ISSUE THREAD

**Issue by shipperizer** [canonical/iam-bundle#50]
### Bug Description

Scheduled workflows kept failing on the master/main branch for quite a while

https://github.com/canonical/iam-bundle/actions/workflows/on_schedule.yaml

we need to figure out why and understand what is the different with the `track/0.1` branch where all is plain sailing

### To Reproduce

see https://github.com/canonical/iam-bundle/actions/workflows/on_schedule.yaml

### Environment

main branch

### Relevant log output

```shell
https://github.com/canonical/iam-bundle/actions/workflows/on_schedule.yaml
```

**Comment by nsklikas** [comment]
I think that this was fixed by https://github.com/canonical/iam-bundle/pull/54 (specifically the bump of the login-ui revision). Can we close it?
